package Routes

import (
	"github.com/Shawket4/Dentex/Controllers"
	"github.com/Shawket4/Dentex/Messaging"
	"github.com/Shawket4/Dentex/Middleware"
	"github.com/gin-gonic/gin"
)

func ConfigRoutes(router *gin.Engine) {
	public := router.Group("/api")
	public.POST("/login", Controllers.Login)
	public.POST("/RegisterDemo", Controllers.RegisterDemo)
	authorized := router.Group("/api/protected")
	authorized.Use(Middleware.JwtAuthMiddleware())
	authorized.GET("/user", Controllers.CurrentUser)
	authorized.POST("/RegisterPatient", Controllers.RegisterPatient)
	authorized.POST("/RegisterPrescription", Controllers.RegisterPrescription)
	authorized.POST("/GetPatientPrescriptions", Controllers.GetPatientPrescriptions)
	authorized.POST("/RegisterAppointment", Controllers.RegisterAppointment)
	authorized.POST("/RegisterTreatment", Controllers.RegisterTreatment)
	authorized.POST("/ChangeAppointmentPaymentStatus", Controllers.ChangeAppointmentPaymentStatus)
	authorized.POST("/ChangeAppointmentCompletionStatus", Controllers.ChangeAppointmentCompletionStatus)
	authorized.GET("/GetDoctorPatients", Controllers.GetDoctorPatients)
	authorized.GET("/GetFavouritePatients", Controllers.GetFavouritePatients)
	authorized.POST("/EditPatientFavouriteStatus", Controllers.EditPatientFavouriteStatus)
	authorized.GET("/GetDoctorAppointments", Controllers.GetDoctorAppointments)
	authorized.GET("/GetDoctorTreatments", Controllers.GetDoctorTreatments)
	authorized.POST("/GetPatientTeethMap", Controllers.GetPatientTeethMap)
	authorized.POST("/EditTeethMap", Controllers.EditTeethMap)
	authorized.POST("/GetPatientDetails", Controllers.GetPatientDetails)
	authorized.GET("/GetDoctorSchedule", Controllers.GetDoctorSchedule)
	authorized.GET("/GetDoctorEarnings", Controllers.GetDoctorEarnings)
	authorized.POST("/GetToothHistory", Controllers.GetToothHistory)
	authorized.POST("/Search", Controllers.Search)
	authorized.POST("/DeletePatient", Middleware.CheckObjectOwnerShip("Patient"), Controllers.DeletePatient)
	authorized.POST("/DeleteTreatment", Middleware.CheckObjectOwnerShip("Treatment"), Controllers.DeleteTreatment)
	authorized.POST("/DeleteAppointment", Middleware.CheckObjectOwnerShip("Appointment"), Controllers.DeleteAppointment)
	authorized.POST("/DeletePrescription", Middleware.CheckObjectOwnerShip("Prescription"), Controllers.DeletePrescription)
	authorized.POST("EditAppointment", Middleware.CheckObjectOwnerShip("Appointment"), Controllers.EditAppointment)
	authorized.POST("/EditPatient", Middleware.CheckObjectOwnerShip("Patient"), Controllers.EditPatient)
	authorized.POST("/EditTreatment", Middleware.CheckObjectOwnerShip("Treatment"), Controllers.EditTreatment)
	authorized.POST("/EditPrescription", Middleware.CheckObjectOwnerShip("Prescription"), Controllers.EditPrescription)
	authorized.POST("/RegisterBraces", Controllers.RegisterBraces)
	authorized.POST("/RegisterBracesAppointment", Controllers.RegisterBracesAppointment)
	authorized.POST("/LinkDeviceToken", Messaging.LinkDeviceToken)
	authorized.POST("/UnlinkDeviceToken", Messaging.UnlinkDeviceToken)
	// public.POST("/SendApi", Messaging.SendApi)
	// authorized.GET("/GetDoctorWorkingHours", Controllers.GetDoctorWorkingHours)
	adminRoutes := router.Group("/api/admin")
	adminRoutes.Use(Middleware.JwtAuthMiddleware())
	adminRoutes.Use(Middleware.PermissionCheckAdmin())
	adminRoutes.POST("/register", Controllers.Register)
	adminRoutes.POST("/RegisterDoctor", Controllers.RegisterDoctor)
	adminRoutes.GET("/GetAllPatients", Controllers.GetAllPatients)
	adminRoutes.GET("/GetAllDoctors", Controllers.GetAllDoctors)
	adminRoutes.POST("DeleteDoctor", Controllers.DeleteDoctor)
	router.Static("/Web", "./Static")
	router.Static("/Welcome", "./Welcome")
}
